- name: Configure Lambda
  hosts: localhost
  gather_facts: false

 # Your lambda task details
  tasks:
    - name: Create Lambda function
      lambda:
        name: my-lambda-function
        handler: index.handler
        runtime: nodejs14.x
        role: arn:aws:iam::123456789012:role/lambda-execution-role
        function_timeout: 30
        state: present
      register: lambda_result

    - name: Print Lambda function info
      debug:
        var: lambda_result
