language: node_js

dist: trusty
sudo: false

node_js:
  - "8.9.4"

install:
  - yarn

before_script:
  - jdk_switcher use oraclejdk8
  - npm run lint

  #order of jobs to run
stages: 
  - Springboard Chrome Regression Suite 1 
  - Springboard Chrome Regression Suite 2 
  - Springboard Chrome Scenario Tests 3
  - Agent Tool Kit Endpoint Regression Suite 4 

jobs:
  include:
  #sba first suite
    - stage: Springboard Chrome Regression Suite 1 
      env: SBA='Refinance Joint Texas QA4' 
      script: nightwatch tests/7_travis/travisSuite/qa8/04travisRefiJoint.js --env qa4 -c nightwatch.conf.TRAVIS.js

    - stage: Springboard Chrome Regression Suite 1
      env: SBA='P2D Joint California QA5' 
      script: nightwatch tests/7_travis/travisSuite/qa8/03travisP2dJoint.js --env qa5 -c nightwatch.conf.TRAVIS.js

    - stage: Springboard Chrome Regression Suite 1
      env: SBA='P2P Joint Minnesota QA6' 
      script: nightwatch tests/7_travis/travisSuite/qa8/05travisP2pJoint.js --env qa7 -c nightwatch.conf.TRAVIS.js
    
    - stage: Springboard Chrome Regression Suite 1
      env: SBA='Verify Zip Codes QA7' 
      script: nightwatch tests/2_scenarioTests/ssnZips/1_checkZipcodes.js --env qa7 -c nightwatch.conf.TRAVIS.js

    
   # sba second suite    
    - stage: Springboard Chrome Regression Suite 2 
      env: SBA='Verify Max. Income On QA4' 
      script: nightwatch tests/2_scenarioTests/ssnZips/1_checkZipcodes.js --env qa4 -c nightwatch.conf.TRAVIS.js
      
    - stage: Springboard Chrome Regression Suite 2 
      env: SBA='P2D Single Florida QA5' 
      script: nightwatch tests/7_travis/travisSuite/qa7/02travisP2DSingle.js --env qa5 -c nightwatch.conf.TRAVIS.js

    - stage: Springboard Chrome Regression Suite 2 
      env: SBA='P2P Single California QA6' 
      script: nightwatch tests/7_travis/travisSuite/qa7/03travisP2PSingle.js --env qa7 -c nightwatch.conf.TRAVIS.js 

    - stage: Springboard Chrome Regression Suite 2 
      env: SBA='Refinance Single Texas QA7' 
      script: nightwatch tests/7_travis/travisSuite/qa7/01travisRefiSingle.js --env qa7 -c nightwatch.conf.TRAVIS.js 
    
 #sba third suite    
    - stage: Springboard Chrome Scenario Tests 3 
      env: SBA='Verify Min. Income Sandbox' 
      script: nightwatch tests/2_scenarioTests/income/1_minIncomeSingle.js --env sandbox -c nightwatch.conf.TRAVIS.js 
    
    - stage: Springboard Chrome Scenario Tests 3 
      env: SBA='Verify Max. Income On DEV' 
      script: nightwatch tests/2_scenarioTests/income/2_minIncomeJoint.js --env dev -c nightwatch.conf.TRAVIS.js

    - stage: Springboard Chrome Scenario Tests 3 
      env: SBA='P2D ATK On QA5' 
      script: nightwatch tests/1_atkTravis/p2d/p2dRun.js --env qa5 -c nightwatch.conf.TRAVIS.js 
    
    - stage: Springboard Chrome Scenario Tests 3 
      env: SBA='Refinance ATK On QA6' 
      script: nightwatch tests/1_atkTravis/refi/refiRun.js --env qa6 -c nightwatch.conf.TRAVIS.js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - distribution.qaengineering@springboardauto.com
    on_success: always